Repository workadventure/workadventure, pull requests merged in 2021-09, with the labels that each got.

#1402 FEATURE: improved the mediaStore code to disable tracks instead of deleting them
  front/src/Components/MyCamera.svelte
  front/src/Phaser/Game/GameScene.ts
  front/src/Stores/MediaStore.ts
  front/src/Stores/ScreenSharingStore.ts
  front/src/WebRtc/SimplePeer.ts
  front/src/WebRtc/VideoPeer.ts
Labels: deploy

#1410 FIX: fixed a circular dependancy in stores
  front/src/Components/Video/PresentationLayout.svelte
  front/src/Phaser/Game/GameScene.ts
  front/src/Stores/AudioManagerStore.ts
  front/src/Stores/MediaStore.ts
  front/src/Stores/PeerStore.ts
  front/src/Stores/ScreenSharingStore.ts
  front/src/Stores/VideoFocusStore.ts
  front/src/WebRtc/SimplePeer.ts
  front/src/WebRtc/VideoPeer.ts
Labels: deploy

#1342 Emote silent zone
  front/src/Components/CameraControls.svelte
  front/src/Components/MyCamera.svelte
  front/src/Phaser/Entity/Character.ts
  front/src/Phaser/Game/EmoteManager.ts
  front/src/Phaser/Game/GameScene.ts
  front/src/Phaser/Player/Player.ts
  front/src/Stores/MediaStore.ts
  front/style/style.scss
Labels: enhancement

#1415 FIX: reimplemented the old stream behavior on bad navigators like chrome
  front/src/Components/HelpCameraSettings/HelpCameraSettingsPopup.svelte
  front/src/Stores/MediaStore.ts
  front/src/WebRtc/DeviceUtils.ts
Labels: deploy

#1431 FIX: the video element should not have a bigger height than its container
  front/src/Components/Video/VideoMediaBox.svelte
  front/src/WebRtc/VideoPeer.ts
  front/style/mobile-style.scss
  front/style/style.scss
Labels: deploy

#1439 Fix disconnects after 5 minutes in Chrome
  back/src/Enum/EnvironmentVariable.ts
  pusher/src/Enum/EnvironmentVariable.ts
Labels: bug

#1457 fix yarn install not working
  front/Dockerfile
Labels: deploy
