Repository workadventure/workadventure, pull requests merged in 2022-09, with the labels that each got.

#2560 remove game quality setting and references to it
  front/src/Components/Menu/SettingsSubMenu.svelte
  front/src/Connexion/LocalUserStore.ts
  front/src/i18n/ca-ES/menu.ts
  front/src/i18n/de-DE/menu.ts
  front/src/i18n/en-US/menu.ts
  front/src/i18n/es-ES/menu.ts
  front/src/i18n/fr-FR/menu.ts
  front/src/i18n/pt-BR/menu.ts
  front/src/i18n/zh-CN/menu.ts
  front/src/index.ts
Labels: deploy

#2575 [Draft] Passing images as artifacts between jobs
  .github/workflows/build-test-and-deploy.yml
  docker-compose.e2e.yml
Labels: deploy

#2587 Updates some action bar icons
  front/src/Components/images/camera-off.png
  front/src/Components/images/microphone-off.png
  front/src/Components/images/screenshare-off.png
  front/src/Components/images/screenshare-on.png
  pusher/src/Services/OpenIDClient.ts
Labels: deploy

#2600 Makes menu more responsive
  front/src/Components/Menu/Menu.svelte
  front/src/Components/Menu/ProfileSubMenu.svelte
Labels: deploy

#2645 Fixing Redis reconnect
  back/package.json
  back/src/Services/RedisClient.ts
  back/yarn.lock
Labels: bug

#2598 Enable disable chat and chat upload feature
  .env.template
  back/src/Enum/EnvironmentVariable.ts
  back/src/Model/GameRoom.ts
  back/src/Services/MucManager.ts
  contrib/docker/.env.prod.template
  contrib/docker/docker-compose.prod.yaml
  contrib/docker/docker-compose.single-domain.yaml
  docker-compose.yaml
  front/chat/src/Components/ChatMessageForm.svelte
  front/chat/src/Event/IframeEvent.ts
  front/chat/src/Event/SettingsEvent.ts
  front/chat/src/IframeListener.ts
  front/chat/src/Stores/ChatStore.ts
  front/chat/src/Xmpp/MucRoom.ts
  front/chat/src/i18n/en-US/index.ts
  front/chat/src/i18n/fr-FR/index.ts
  front/src/Api/Events/SettingsEvent.ts
  front/src/Api/IframeListener.ts
  front/src/Components/Chat/Chat.svelte
  front/src/Connexion/Room.ts
  front/src/Connexion/RoomConnection.ts
  front/src/Enum/EnvironmentVariable.ts
  front/src/Phaser/Game/GameMapPropertiesListener.ts
  messages/JsonMessages/MapDetailsData.ts
  pusher/src/Controller/IoSocketChatController.ts
  pusher/src/Enum/EnvironmentVariable.ts
  pusher/src/Services/LocalAdmin.ts
  pusher/src/Services/XmppClient.ts
  tests/tests/chat.spec.ts
Labels: build

#2638 Update images for the compatibility with arm
  docker-compose.yaml
Labels: refractoring
