Repository workadventure/workadventure, pull requests merged in 2022-07, with the labels that each got.

#2367 Adds different breakpoints support for the chat
  front/src/Components/Chat/Chat.svelte
Labels: deploy

#2295 change camera offset when entering / leaving bubble conversation
  front/src/Phaser/Game/GameScene.ts
Labels: deploy

#2358 Upgrade map if needed
  back/package.json
  back/src/Model/GameRoom.ts
  back/src/Services/MapFetcher.ts
  back/src/Services/ModeratorTagFinder.ts
  back/src/Services/VariablesManager.ts
  back/yarn.lock
  docs/maps/api-room.md
  docs/maps/camera.md
  docs/maps/meeting-rooms.md
  docs/maps/opening-a-website.md
  docs/maps/special-zones.md
  docs/maps/variables.md
  front/package.json
  front/src/Api/iframe/Area/Area.ts
  front/src/Api/iframe/room.ts
  front/src/Phaser/Components/TextUtils.ts
  front/src/Phaser/Game/AreaManager.ts
  front/src/Phaser/Game/GameMap.ts
  front/src/Phaser/Game/GameMapPropertiesListener.ts
  front/src/Phaser/Game/GameScene.ts
  front/src/Phaser/Game/SharedVariablesManager.ts
  front/src/Phaser/Game/StartPositionCalculator.ts
  front/src/Phaser/Items/Computer/computer.ts
  front/src/Phaser/Items/ItemFactoryInterface.ts
  front/src/Phaser/Map/ITiledMap.ts
  front/src/Phaser/Map/LayersFlattener.ts
  front/src/Phaser/Map/PropertyUtils.ts
  front/tests/Phaser/Map/LayersIteratorTest.ts
  front/yarn.lock
Labels: deploy

#2370 Create new emoji sub menu
  back/src/Model/GameRoom.ts
  back/src/Model/User.ts
  back/src/Services/SocketManager.ts
  front/src/Administration/AnalyticsClient.ts
  front/src/Components/CameraControls.svelte
  front/src/Components/Chat/UsersList.svelte
  front/src/Components/EmoteMenu/EmoteMenu.svelte
  front/src/Components/MainLayout.svelte
  front/src/Components/Menu/GuestSubMenu.svelte
  front/src/Components/Menu/Menu.svelte
  front/src/Components/Menu/MenuIcon.svelte
  front/src/Components/Menu/ProfileSubMenu.svelte
  front/src/Components/Video/ScreenSharingMediaBox.svelte
  front/src/Components/images/close.png
  front/src/Components/images/icon-workadventure-white.png
  front/src/Components/images/pen.png
  front/src/Connexion/LocalUserStore.ts
  front/src/Connexion/RoomConnection.ts
  front/src/Phaser/Game/GameScene.ts
  front/src/Stores/EmoteStore.ts
  front/src/Stores/MenuStore.ts
  front/src/i18n/ca-ES/menu.ts
  front/src/i18n/de-DE/menu.ts
  front/src/i18n/en-US/menu.ts
  front/src/i18n/es-ES/menu.ts
  front/src/i18n/fr-FR/menu.ts
  front/src/i18n/pt-BR/menu.ts
  front/src/i18n/zh-CN/menu.ts
  front/style/style.scss
  front/style/wa-theme/action-menu-bar.scss
  messages/protos/messages.proto
  pusher/src/Controller/AuthenticateController.ts
  pusher/src/Controller/IoSocketController.ts
  pusher/src/Model/Websocket/ExSocketInterface.ts
  pusher/src/Services/AdminApi.ts
  pusher/src/Services/LocalAdmin.ts
  pusher/src/Services/SocketManager.ts
  tests/tests/iframe_script.spec.ts
  tests/tests/translate.spec.ts
Labels: deploy, deploy-connect-to-admin

#2397 Reading the new "class" property instead of "type"
  back/src/Services/ModeratorTagFinder.ts
  back/src/Services/VariablesManager.ts
  front/src/Api/iframe/Area/Area.ts
  front/src/Phaser/Game/GameMap.ts
  front/src/Phaser/Game/GameScene.ts
  front/src/Phaser/Game/SharedVariablesManager.ts
Labels: bug

#2403 Trying to implement more robust ping/pong mechanism
  pusher/src/Controller/IoSocketController.ts
Labels: bug

#2404 Add documentation on ALL scripting API functions
  docs/maps/api-room.md
  docs/maps/api-ui.md
  front/src/Api/iframe/Ui/UIWebsite.ts
  front/src/Api/iframe/area.ts
  front/src/Api/iframe/camera.ts
  front/src/Api/iframe/chat.ts
  front/src/Api/iframe/controls.ts
  front/src/Api/iframe/nav.ts
  front/src/Api/iframe/player.ts
  front/src/Api/iframe/room.ts
  front/src/Api/iframe/sound.ts
  front/src/Api/iframe/ui.ts
  front/src/Api/iframe/website.ts
  front/src/Phaser/Components/Loader.ts
  front/src/i18n/de-DE/companion.ts
  front/src/iframe_api.ts
Labels: refractoring

#2444 Modify the way to add a message on a pr
  .github/workflows/build-and-deploy.yml
Labels: deploy
