Repository workadventure/workadventure, pull requests merged in 2022-04, with the labels that each got.

#2023 New custom woka scene full clothes
  front/src/Phaser/Components/CustomizeWoka/CustomWokaPreviewer.ts
  front/src/Phaser/Components/CustomizeWoka/WokaBodyPartSlot.ts
  front/src/Phaser/Components/Ui/IconButton.ts
  front/src/Phaser/Login/CustomizeScene.ts
  front/src/WebRtc/VideoPeer.ts
Labels: deploy

#2020 Global voice-indicators
  back/src/Model/GameRoom.ts
  back/src/Model/User.ts
  back/src/Services/SocketManager.ts
  front/src/Connexion/ConnexionModels.ts
  front/src/Connexion/RoomConnection.ts
  front/src/Phaser/Game/GameScene.ts
  messages/protos/messages.proto
  pusher/src/Model/Zone.ts
Labels: deploy

#1994 New custom woka scene
  front/package.json
  front/public/resources/icons/icon_accessory.png
  front/public/resources/icons/icon_body.png
  front/public/resources/icons/icon_clothes.png
  front/public/resources/icons/icon_eyes.png
  front/public/resources/icons/icon_hair.png
  front/public/resources/icons/icon_hat.png
  front/public/resources/icons/icon_turn.png
  front/public/resources/tilesets/floor_tiles.png
  front/src/Components/App.svelte
  front/src/Components/CustomCharacterScene/CustomCharacterScene.svelte
  front/src/Phaser/Components/CustomizeWoka/CustomWokaPreviewer.ts
  front/src/Phaser/Components/CustomizeWoka/WokaBodyPartSlot.ts
  front/src/Phaser/Components/Ui/Button.ts
  front/src/Phaser/Components/Ui/IconButton.ts
  front/src/Phaser/Entity/Character.ts
  front/src/Phaser/Entity/CustomizedCharacter.ts
  front/src/Phaser/Helpers/TexturesHelper.ts
  front/src/Phaser/Login/AbstractCharacterScene.ts
  front/src/Phaser/Login/CustomizeScene.ts
  front/src/Phaser/Login/EntryScene.ts
  front/src/Phaser/Login/SelectCharacterScene.ts
  front/src/Phaser/Player/Animation.ts
  front/src/Phaser/Services/WaScaleManager.ts
  front/src/Stores/CustomCharacterStore.ts
  front/src/WebRtc/VideoPeer.ts
  front/yarn.lock
  pusher/src/Enum/PlayerTextures.ts
Labels: deploy

#2028 Enable right click on overlay
  front/src/index.ts
Labels: deploy

#2074 Add chinese translation
  front/src/i18n/zh-CN/audio.ts
  front/src/i18n/zh-CN/camera.ts
  front/src/i18n/zh-CN/chat.ts
  front/src/i18n/zh-CN/companion.ts
  front/src/i18n/zh-CN/emoji.ts
  front/src/i18n/zh-CN/error.ts
  front/src/i18n/zh-CN/follow.ts
  front/src/i18n/zh-CN/index.ts
  front/src/i18n/zh-CN/login.ts
  front/src/i18n/zh-CN/menu.ts
  front/src/i18n/zh-CN/report.ts
  front/src/i18n/zh-CN/trigger.ts
  front/src/i18n/zh-CN/warning.ts
  front/src/i18n/zh-CN/woka.ts
Labels: good first issue

#2077 Read properties from Tiled objects
  docs/maps/camera.md
  docs/maps/images/camera/4_add_zone_type.png
  docs/maps/images/camera/5_click_add_property.png
  docs/maps/images/camera/7_make_sure_checked.png
  docs/maps/meeting-rooms.md
  docs/maps/opening-a-website.md
  docs/maps/special-zones.md
  docs/maps/wa-maps.md
  front/src/Api/Events/ChangeAreaEvent.ts
  front/src/Api/Events/IframeEvent.ts
  front/src/Api/IframeListener.ts
  front/src/Phaser/Game/GameMap.ts
  front/src/Phaser/Game/GameMapProperties.ts
  front/src/Phaser/Game/GameMapPropertiesListener.ts
  front/src/Phaser/Game/GameScene.ts
  maps/tests/Pathfinding/map.json
  maps/tests/Pathfinding/script.php
  maps/tests/index.html
  maps/tests/tiled_objects.json
Labels: deploy

#2053 Reworking the wording of "away" mode
  front/src/Components/Menu/SettingsSubMenu.svelte
  front/src/Components/images/info.svg
  front/src/i18n/de-DE/menu.ts
  front/src/i18n/en-US/menu.ts
  front/src/i18n/fr-FR/menu.ts
Labels: deploy

#2091 Availability Statuses
  back/src/Model/GameRoom.ts
  back/src/Model/User.ts
  back/src/RoomManager.ts
  back/src/Services/SocketManager.ts
  back/tests/PositionNotifierTest.ts
  front/public/resources/icons/icon_status_indicator_inside.png
  front/public/resources/icons/icon_status_indicator_outline.png
  front/src/Api/desktop/index.ts
  front/src/Components/CameraControls.svelte
  front/src/Components/MyCamera.svelte
  front/src/Connexion/ConnexionModels.ts
  front/src/Connexion/RoomConnection.ts
  front/src/Phaser/Components/PlayerStatusDot.ts
  front/src/Phaser/Entity/Character.ts
  front/src/Phaser/Game/GameMapPropertiesListener.ts
  front/src/Phaser/Game/GameScene.ts
  front/src/Phaser/Game/PlayerInterface.ts
  front/src/Phaser/Game/PlayerMovement.ts
  front/src/Phaser/Helpers/TexturesHelper.ts
  front/src/Phaser/Player/Player.ts
  front/src/Stores/MediaStore.ts
  front/src/Stores/PlayersStore.ts
  maps/tests/index.html
  maps/tests/status_indicator.json
  messages/protos/messages.proto
  pusher/src/Controller/IoSocketController.ts
  pusher/src/Model/Zone.ts
  pusher/src/Services/SocketManager.ts
Labels: deploy

#2075 Refactoring Error Screen
  front/src/Components/App.svelte
  front/src/Components/UI/ErrorScreen.svelte
  front/src/Components/images/logo-min-white.png
  front/src/Components/images/reload.png
  front/src/Connexion/RoomConnection.ts
  front/src/Phaser/Login/EntryScene.ts
  front/src/Phaser/Reconnecting/ErrorScene.ts
  front/src/Phaser/Reconnecting/WAError.ts
  front/src/Stores/ErrorScreenStore.ts
  messages/JsonMessages/ErrorApiData.ts
  messages/protos/messages.proto
  pusher/package.json
  pusher/src/Controller/AuthenticateController.ts
  pusher/src/Controller/BaseHttpController.ts
  pusher/src/Controller/IoSocketController.ts
  pusher/src/Controller/MapController.ts
  pusher/src/Services/AdminApi.ts
  pusher/src/Services/AdminInterface.ts
  pusher/src/Services/LocalAdmin.ts
  pusher/src/Services/SocketManager.ts
Labels: deploy, deploy-connect-to-admin

#2117 Fixing compatibility issue with Safari 14-
  front/package.json
  front/yarn.lock
Labels: deploy

#2143 send removeOutline flag if needed
  back/src/Model/User.ts
Labels: deploy

#2144 Refreshing map URL
  back/src/Model/GameRoom.ts
  back/src/Services/SocketManager.ts
Labels: bug
