Repository workadventure/workadventure, pull requests merged in 2023-01, with the labels that each got.

#2938 Implement more logs on players behavior
  play/src/front/Debug/DebugManager.ts
  play/src/front/Phaser/Game/GameScene.ts
  play/src/front/Phaser/Game/RemotePlayersRepository.ts
  play/src/front/vite-env.d.ts
  play/src/svelte.ts
Labels: deploy

#2941 Add more logs
  play/src/front/Logger/MessageUI.ts
  play/src/front/Phaser/Game/GameScene.ts
  play/src/front/Phaser/Game/RemotePlayersRepository.ts
  play/src/front/Utils/Debuggers.ts
Labels: deploy

#2959 Fixing deployment of map-storage
  deeployer.libsonnet
  docker-compose.e2e.yml
Labels: deploy

#2960 Upload demo maps in CD
  .github/workflows/build-test-and-deploy.yml
  deeployer.libsonnet
Labels: deploy

#2961 Making OPID_WOKA_NAME_POLICY optional
  libs/messages/src/JsonMessages/OpidWokaNamePolicy.ts
  play/src/pusher/enums/EnvironmentVariable.ts
Labels: deploy

#2973 Hotfix: Fix emoji issue
  chat/index.html
  chat/src/Components/Timeline/ChatActiveThreadTimeline.svelte
  play/src/front/Components/ActionBar/ActionBar.svelte
  play/src/front/Components/EmoteMenu/EmoteMenu.svelte
  play/src/front/Phaser/Entity/Character.ts
  play/src/front/Phaser/Game/GameScene.ts
  play/src/front/Stores/EmoteStore.ts
Labels: deploy

#2982 Fix emoji local storage issue
  play/src/front/Administration/AnalyticsClient.ts
  play/src/front/Components/ActionBar/ActionBar.svelte
  play/src/front/Connexion/LocalUserStore.ts
  play/src/front/Stores/EmoteStore.ts
  play/src/front/Stores/Utils/emojiSchema.ts
Labels: deploy

#2991 Using multiple cache-from images in build process
  .github/workflows/build-test-and-deploy.yml
Labels: build

#2990 Setting up a map-storage deployed in multi-domain mode in CD
  .github/workflows/build-test-and-deploy.yml
  cd/README.md
  cd/map-storage-traefik-ingress-route.tmpl.yaml
  deeployer.libsonnet
Labels: deploy, deploy-connect-to-admin

#2974 add tooltip to sidebar
  play/src/front/Components/MapEditor/MapEditorSideBar.svelte
  play/src/front/Components/Util/Tooltip.svelte
Labels: deploy
