Repository workadventure/workadventure, pull requests merged in 2023-04, with the labels that each got.

#3153 Room API
  .env.template
  .github/workflows/build-test-and-deploy.yml
  .github/workflows/continuous_integration.yml
  .github/workflows/iframe-api-push-to-npm.yml
  .github/workflows/room-api-push-to-npm.yml
  .vscode/launch.json
  back/src/Model/GameRoom.ts
  back/src/RoomManager.ts
  back/src/Services/SocketManager.ts
  back/src/Services/VariablesManager.ts
  back/src/SpaceManager.ts
  contrib/docker/.env.prod.template
  contrib/docker/.gitignore
  contrib/docker/docker-compose.prod.yaml
  contrib/docker/docker-compose.single-domain.yaml
  deeployer.libsonnet
  docker-compose.yaml
  docs/dev/README.md
  docs/dev/roomAPI.md
  libs/room-api-clients/room-api-client-js/.eslintignore
  libs/room-api-clients/room-api-client-js/.eslintrc.json
  libs/room-api-clients/room-api-client-js/.gitignore
  libs/room-api-clients/room-api-client-js/LICENSE.txt
  libs/room-api-clients/room-api-client-js/README.md
  libs/room-api-clients/room-api-client-js/package-lock.json
  libs/room-api-clients/room-api-client-js/package.json
  libs/room-api-clients/room-api-client-js/src/compiled_proto/.gitignore
  libs/room-api-clients/room-api-client-js/src/example.ts
  libs/room-api-clients/room-api-client-js/src/index.ts
  libs/room-api-clients/room-api-client-js/tsconfig.json
  map-storage/src/MapStorageServer.ts
  messages/protos/messages.proto
  messages/protos/room-api.proto
  messages/protos/services.proto
  package-lock.json
  play/package.json
  play/src/pusher/enums/EnvironmentVariable.ts
  play/src/pusher/enums/EnvironmentVariableValidator.ts
  play/src/room-api/RoomApiServer.ts
  play/src/room-api/authentication/AdminAuthenticator.ts
  play/src/room-api/authentication/AuthenticatorInterface.ts
  play/src/room-api/authentication/LocalAuthenticator.ts
  play/src/room-api/guards/AuthenticationGuard.ts
  play/src/room-api/types/GuardError.ts
  play/src/server.ts
  play/tests/room-api/RoomApiServer.test.ts
  play/tests/room-api/authentication/AdminAuthenticator.test.ts
  play/tests/room-api/authentication/LocalAuthenticator.test.ts
  play/tests/room-api/guards/AuthenticationGuard.test.ts
  tests/package.json
  tests/tests/room-api.spec.ts
Labels: deploy, deploy-connect-to-admin

#3213 Fixing setInterval not cleared on microphone state
  play/src/front/Components/EmbedScreens/CamerasContainer.svelte
  play/src/front/Components/Video/MediaBox.svelte
Labels: bug, deploy

#3215 Fixing work with relative WAM URLs
  play/src/front/Phaser/Game/GameScene.ts
Labels: bug, build

#3214 Turning off microphone when "camera energy saving" is on
  play/src/front/Components/EnableCamera/EnableCameraScene.svelte
  play/src/front/Components/Video/VideoMediaBox.svelte
  play/src/front/Phaser/Login/SelectCharacterScene.ts
  play/src/front/Stores/MediaStore.ts
  play/src/front/WebRtc/SimplePeer.ts
Labels: deploy

#3218 Adding a temporary test mode to debug Chrome heavy throttling
  play/index.html
Labels: deploy

#3206 Implement Healthchecks on Docker Compose Files
  .github/workflows/build-test-and-deploy.yml
  back/Dockerfile
  back/src/Enum/EnvironmentVariable.ts
  back/src/Enum/EnvironmentVariableValidator.ts
  back/src/Model/GameRoom.ts
  chat/Dockerfile
  contrib/docker/docker-compose.prod.yaml
  contrib/docker/tests/docker-compose.test-maps.yaml
  deeployer.libsonnet
  docker-compose.e2e.yml
  docker-compose.yaml
  libs/map-editor/src/MapFetcher.ts
  libs/messages/src/JsonMessages/MapDetailsData.ts
  map-storage/Dockerfile
  map-storage/src/Upload/UploadController.ts
  map-storage/src/index.ts
  play/Dockerfile
  play/src/pusher/enums/EnvironmentVariableValidator.ts
  tests/tests/map_storage_upload.spec.ts
  wait-proto.sh
Labels: enhancement, deploy
