Repository workadventure/workadventure, pull requests merged in 2024-11, with the labels that each got.

#4377 Fixing missing content-type for the matrix-callback route
  play/src/pusher/controllers/AuthenticateController.ts
Labels: bug

#4379 Tagging the master branch with the commit SHA
  .github/workflows/build-test-and-deploy.yml
Labels: build

#4382 Easy image pull secrets configuration
  contrib/helm/templates/_helpers.tpl
  contrib/helm/templates/back-statefulset.yaml
  contrib/helm/templates/icon-deployment.yaml
  contrib/helm/templates/maps-deployment.yaml
  contrib/helm/templates/mapstorage-deployment.yaml
  contrib/helm/templates/play-deployment.yaml
  contrib/helm/templates/pull-secret.yaml
  contrib/helm/templates/uploader-deployment.yaml
  contrib/helm/values.yaml
Labels: deploy

#4342 Migrating external-module outside project
  libs/messages/src/JsonMessages/MapDetailsData.ts
  play/Dockerfile
  play/src/external-modules/ms-teams/Components/AddTeamsMeetingAreaPropertyButton.svelte
  play/src/external-modules/ms-teams/Components/TeamsActionBar.svelte
  play/src/external-modules/ms-teams/Components/TeamsAvailabilityStatusInformation.svelte
  play/src/external-modules/ms-teams/Components/TeamsMeetingAreaPropertyEditor.svelte
  play/src/external-modules/ms-teams/Components/TeamsPopupLauncher.svelte
  play/src/external-modules/ms-teams/Components/TeamsPopupMeetingNotCreated.svelte
  play/src/external-modules/ms-teams/Components/TeamsPopupReconnect.svelte
  play/src/external-modules/ms-teams/Components/TeamsPopupStatus.svelte
  play/src/external-modules/ms-teams/Components/images/business.svg
  play/src/external-modules/ms-teams/Components/images/check.svg
  play/src/external-modules/ms-teams/Components/images/reload.svg
  play/src/external-modules/ms-teams/Components/images/warning.svg
  play/src/external-modules/ms-teams/MSTeamsInterface.ts
  play/src/external-modules/ms-teams/MapEditor/types.ts
  play/src/external-modules/ms-teams/Services/TeamsOnlineMeeting.ts
  play/src/external-modules/ms-teams/Services/TeamsVirtualEvent.ts
  play/src/external-modules/ms-teams/Services/Todolist.ts
  play/src/external-modules/ms-teams/index.ts
  play/src/front/Chat/Components/Room/Message/MessageVideoFile.svelte
  play/src/front/Components/ActionBar/ActionBar.svelte
  play/src/front/Components/UI/Notification.svelte
  play/src/front/Connection/Room.ts
  play/src/front/ExternalModule/ExtensionModule.ts
  play/src/front/Phaser/Game/GameScene.ts
  play/src/front/external-modules/.gitignore
Labels: deploy

#4296 Redesigning chat
  libs/tailwind/style/tailwind.scss
  play/src/front/Chat/ChatSidebar.svelte
  play/src/front/Chat/Components/Avatar.svelte
  play/src/front/Chat/Components/Chat.svelte
  play/src/front/Chat/Components/ChatError.svelte
  play/src/front/Chat/Components/ChatHeader.svelte
  play/src/front/Chat/Components/Room/CreateRoomOrFolderOption.svelte
  play/src/front/Chat/Components/Room/EmojiButton.svelte
  play/src/front/Chat/Components/Room/Message.svelte
  play/src/front/Chat/Components/Room/Message/MessageAudioFile.svelte
  play/src/front/Chat/Components/Room/Message/MessageFile.svelte
  play/src/front/Chat/Components/Room/Message/MessageFileInput.svelte
  play/src/front/Chat/Components/Room/Message/MessageImage.svelte
  play/src/front/Chat/Components/Room/Message/MessageText.svelte
  play/src/front/Chat/Components/Room/Message/MessageVideoFile.svelte
  play/src/front/Chat/Components/Room/MessageEdition.svelte
  play/src/front/Chat/Components/Room/MessageInputBar.svelte
  play/src/front/Chat/Components/Room/MessageOptions.svelte
  play/src/front/Chat/Components/Room/MessageReactions.svelte
  play/src/front/Chat/Components/Room/MessageSystem.svelte
  play/src/front/Chat/Components/Room/Reaction.svelte
  play/src/front/Chat/Components/Room/Room.svelte
  play/src/front/Chat/Components/Room/RoomInvitation.svelte
  play/src/front/Chat/Components/Room/RoomMenu/RoomMenu.svelte
  play/src/front/Chat/Components/Room/RoomMenu/RoomOption.svelte
  play/src/front/Chat/Components/Room/RoomTimeline.svelte
  play/src/front/Chat/Components/RoomFolder.svelte
  play/src/front/Chat/Components/RoomList.svelte
  play/src/front/Chat/Components/ShowMore.svelte
  play/src/front/Chat/Components/UserList/RoomUserList.svelte
  play/src/front/Chat/Components/UserList/User.svelte
  play/src/front/Chat/Components/UserList/UserActionButton.svelte
  play/src/front/Chat/Connection/Matrix/InteractiveAuthSSO.svelte
  play/src/front/Chat/UserProvider/WorldUserProvider.ts
  play/src/front/Chat/images/get-close.png
  play/src/front/Chat/images/loading-small.svelte
  play/src/front/Chat/images/message-smiley.svg
  play/src/front/Components/Icons.ts
  play/src/front/Phaser/Game/GameScene.ts
  play/src/i18n/en-US/chat.ts
  play/src/i18n/fr-FR/chat.ts
  tests/tests/chat/chatUtils.ts
  tests/tests/chat/matrixApi.ts
  tests/tests/chat/matrixChat.spec.ts
  tests/tests/scripting_chat.spec.ts
  tests/tests/userlist.spec.ts
  tests/tests/utils/chat.ts
Labels: deploy
