Repository workadventure/workadventure, pull requests merged in 2025-04, with the labels that each got.

#4690 Fixing E2E test for cowebsites
  tests/tests/scripting_open_cowebsite.spec.ts
Labels: deploy

#4691 Attempt Matrix test E2E fix
  tests/tests/chat/chatUtils.ts
Labels: deploy

#4663 improve enable camera scene
  play/src/front/Components/EnableCamera/EnableCameraScene.svelte
  play/src/front/Components/EnableCamera/SelectCamera.svelte
  play/src/front/Components/EnableCamera/SelectMicrophone.svelte
  play/src/front/Components/EnableCamera/SelectSpeaker.svelte
Labels: deploy

#4729 Removing screen-sharing button if browser does not support it
  play/src/front/Components/ActionBar/MenuIcons/ScreenSharingMenuItem.svelte
  play/src/front/Stores/ScreenSharingStore.ts
Labels: deploy

#4728 Fixed the responsive of the WOKA
  play/src/front/Chat/Components/Avatar.svelte
  play/src/front/Chat/Components/RoomList.svelte
  play/src/front/Components/ActionBar/MenuIcons/ProfileMenu.svelte
  play/src/front/Components/Video/UserName.svelte
  play/src/front/Components/Video/UserTag.svelte
  play/src/front/Components/Video/VideoMediaBox.svelte
  play/src/front/Components/Woka/Woka.svelte
  play/src/front/Components/Woka/WokaFromUserId.svelte
Labels: deploy

#4684 Trigger SAAS pipeline
  .github/workflows/build-test-and-deploy.yml
Labels: deploy, build, linked_to_saas_branch

#4739 Fixing action bar positionning
  play/src/front/Components/MainLayout.svelte
Labels: deploy

#4740 Removing RUN_FROM_GITHUB.
  .github/workflows/build-test-and-deploy.yml
Labels: linked_to_saas_branch

#4693 Fix matrix SAAS tests
  play/src/front/Chat/Utils.ts
  play/src/front/Phaser/Game/GameManager.ts
  play/src/front/Stores/GameSceneStore.ts
  play/src/front/Stores/Utils/waitForStoreValue.ts
  play/src/i18n/en-US/chat.ts
  play/src/i18n/fr-FR/chat.ts
Labels: linked_to_saas_branch

#4752 Fix UI iOS mobile
  play/src/front/Chat/ChatSidebar.svelte
  play/src/front/Chat/Components/ChatHeader.svelte
  play/src/front/Chat/Components/RequiresLoginForChatModal.svelte
  play/src/front/Chat/Components/UserList/UserActionButton.svelte
  play/src/front/Components/Input/ButtonClose.svelte
Labels: deploy

#4756 Fix buttons on popups
  play/src/front/Chat/Components/Room/CreateFolderModal.svelte
  play/src/front/Chat/Connection/Matrix/AccessSecretStorageDialog.svelte
  play/src/front/Chat/Connection/Matrix/AskStartVerificationModal.svelte
  play/src/front/Chat/Connection/Matrix/ChooseDeviceVerificationMethodModal.svelte
  play/src/front/Chat/Connection/Matrix/CreateRecoveryKeyDialog.svelte
  play/src/front/Components/Menu/ResetKeyStorageConfirmationModal.svelte
Labels: build

#4757 space reconnection
  back/src/Model/Space.ts
  play/src/front/Chat/Components/UserList/User.svelte
  play/src/front/Chat/UserProvider/WorldUserProvider.ts
  play/src/front/Connection/ConnectionManager.ts
  play/src/front/Space/SpaceRegistry/SpaceRegistry.ts
  play/src/front/Space/tests/SpaceIntegration.test.ts
  play/src/front/Space/tests/SpaceRegistry.test.ts
  play/src/front/Space/tests/SpaceWatcherSocket.test.ts
Labels: deploy

#4767 Fix UX to user connected or not connected from the chat
  .github/workflows/build-test-and-deploy.yml
  play/src/front/Chat/Components/UserList/User.svelte
  play/src/front/Chat/Components/UserList/UserActionButton.svelte
  play/src/front/Chat/Utils.ts
  play/src/i18n/en-US/chat.ts
  tests/tests/userlist.spec.ts
Labels: to merge

#4766 Fix refresh screen design
  play/src/front/Components/RefreshPrompt.svelte
Labels: to merge

#4765 Fix chat drag drop and bumping message
  play/src/front/Chat/Components/Room/Message.svelte
  play/src/front/Chat/Components/Room/Message/MessageImage.svelte
  play/src/front/Chat/Components/Room/MessageInputBar.svelte
Labels: to merge

#4775 userlist stabilization
  .github/workflows/build-test-and-deploy.yml
  back/src/Model/Space.ts
  play/src/pusher/models/Space.ts
  play/src/pusher/services/SocketManager.ts
Labels: deploy

#4794 In PiP, disabling audio feedback
  play/src/front/Components/Video/PictureInPicture/PictureInPictureAudioWrapper.svelte
Labels: bug, deploy

#4800 Fixing room list
  play/src/front/Components/ActionBar/ActionBarButton.svelte
  play/src/front/Components/ActionBar/MenuIcons/AppsMenuItem.svelte
Labels: bug, build

#4802 Adding back setting renderer via tag
  play/src/front/Components/App.svelte
Labels: bug

#4796 Fix sound missing in full-screen
  play/src/front/Components/MainLayout.svelte
  play/src/front/Components/Video/PictureInPicture.svelte
  play/src/front/Components/Video/PictureInPicture/AudioStream.svelte
  play/src/front/Components/Video/PictureInPicture/AudioStreamWrapper.svelte
Labels: bug, deploy
