Repository workadventure/workadventure, pull requests merged in 2025-09, with the labels that each got.

#5072 Improving map-editor documentation
  docs/map-building/inline-editor/area-editor/broadcast.md
  docs/map-building/inline-editor/area-editor/entry-exit.md
  docs/map-building/inline-editor/area-editor/focusable.md
  docs/map-building/inline-editor/area-editor/index.md
  docs/map-building/inline-editor/area-editor/jitsi.md
  docs/map-building/inline-editor/area-editor/matrix-chat-zone.md
  docs/map-building/inline-editor/area-editor/open-file.md
  docs/map-building/inline-editor/area-editor/open-link.md
  docs/map-building/inline-editor/area-editor/personal-area.md
  docs/map-building/inline-editor/area-editor/restricted-area.md
  docs/map-building/inline-editor/area-editor/silent.md
  docs/map-building/inline-editor/entity-editor/_category_.yml
  docs/map-building/inline-editor/entity-editor/jitsi.md
  docs/map-building/inline-editor/entity-editor/open-file.md
  docs/map-building/inline-editor/entity-editor/open-link.md
  docs/map-building/inline-editor/entity-editor/play-sound.md
  docs/map-building/inline-editor/entity-editor/upload-file.md
Labels: size:M

#5078 Fix ui of global text message component
  play/src/front/Components/TypeMessage/TextMessage.svelte
Labels: size:XS

#5083 Fixing custom Woka lost
  play/src/front/Phaser/Game/GameScene.ts
Labels: deploy, size:XS

#5084 Adding 2 allowed Headers in CORS
  play/src/pusher/app.ts
Labels: deploy, size:XS

#5106 avoid emitting message after leaving space
  play/src/front/Phaser/Game/GameScene.ts
  play/src/front/Space/Space.ts
Labels: size:M

#5107 Fix refresh token
  play/src/pusher/controllers/IoSocketController.ts
Labels: size:M

#5110 Optimizing rendering of Woka pictures
  play/src/front/Chat/Components/Avatar.svelte
  play/src/front/Phaser/Entity/Character.ts
Labels: size:L

#4902 Putting active speakers top of the list
  play/src/front/Components/EmbedScreens/CamerasContainer.svelte
  play/src/front/Livekit/LivekitParticipant.ts
  play/src/front/Livekit/LivekitRoomWatch.ts
  play/src/front/Space/Space.ts
  play/src/front/Space/tests/Space.test.ts
  play/src/front/Space/tests/SpaceFilter.test.ts
  play/src/front/Space/tests/SpaceIntegration.test.ts
  play/src/front/Space/tests/SpaceRegistry.test.ts
  play/src/front/Space/tests/SpaceWatcherSocket.test.ts
  play/src/front/Stores/OrderedStreamableCollectionStore.ts
  play/src/front/Stores/ScreenSharingStore.ts
  play/src/front/Stores/ScriptingVideoStore.ts
  play/src/front/Stores/StableNSorter.ts
  play/src/front/Stores/StreamableCollectionStore.ts
  play/src/front/Streaming/Jitsi/JitsiTrackStreamWrapper.ts
  play/src/front/WebRtc/ScreenSharingPeer.ts
  play/src/front/WebRtc/VideoPeer.ts
  play/tests/front/Stores/StableNSorter.test.ts
Labels: deploy, size:L

#5115 resolve LiveKit integration issues
  back/src/Model/EventProcessorInit.ts
  back/src/Model/Strategies/WebRTCCommunicationStrategy.ts
  back/src/Model/User.ts
  messages/protos/messages.proto
  play/src/front/Chat/Components/UserList/User.svelte
  play/src/front/Chat/Connection/Matrix/MatrixChatConnection.ts
  play/src/front/Chat/Connection/Matrix/tests/MatrixChatConnection.test.ts
  play/src/front/Components/ActionBar/AvailabilityStatus/AvailabilityStatusList.svelte
  play/src/front/Components/PopUp/SayPopUp.svelte
  play/src/front/Phaser/Game/MapEditor/AreasPropertiesListener.ts
  play/src/front/Rules/StatusRules/StatusStrategy/BasicStatusStrategy.ts
  play/src/front/Rules/StatusRules/statusRules.ts
  play/src/front/Stores/MediaStore.ts
  play/src/front/Utils/AvailabilityStatus.ts
Labels: size:M

#5142 Fixing too fast reconnection loop
  back/src/Services/SocketManager.ts
  play/src/pusher/models/SpaceConnection.ts
  play/src/pusher/models/SpaceToBackForwarder.ts
  play/src/pusher/services/SocketManager.ts
  play/tests/pusher/Space.test.ts
Labels: size:M

#5145 Simplifying code with a ForwardableStore
  play/src/front/Phaser/Game/GameScene.ts
  play/src/front/Stores/PeerStore.ts
Labels: size:M

#5154 Removing prepuller
  .github/workflows/build-test-and-deploy.yml
  contrib/helm/templates/prepuller-daemonset.yaml
  contrib/helm/values.yaml
Labels: deploy, size:M

#5156 Fixing error handling in Proximity space
  play/src/front/Chat/Connection/Proximity/ProximityChatRoom.ts
Labels: size:L

#5141 Improve sentry error captureed
  back/src/Services/MessageHelpers.ts
  back/src/Services/SocketManager.ts
  play/src/front/Api/IframeListener.ts
  play/src/front/Chat/Components/Room/RoomTimeline.svelte
  play/src/front/Chat/Connection/Matrix/MatrixClientWrapper.ts
  play/src/front/Components/Menu/SettingsSubMenu.svelte
  play/src/front/Phaser/Game/GameScene.ts
  play/src/front/WebRtc/MediaManager.ts
  play/src/pusher/controllers/AdminController.ts
  play/src/pusher/controllers/AuthenticateController.ts
  play/src/pusher/controllers/IoSocketController.ts
  play/src/pusher/models/SpaceToFrontDispatcher.ts
  play/src/pusher/services/SocketManager.ts
Labels: size:L

#5167 fix double screen share
  play/src/front/WebRtc/ScreenSharingPeer.ts
Labels: size:S

#5164 Map validator: avoid returning empty arrays of errors
  libs/map-editor/src/GameMap/MapValidator.ts
Labels: size:XS

#5151 Fixing the local video feedback in Busy status
  play/src/front/Stores/StreamableCollectionStore.ts
Labels: size:XS

#5177 Improve picture in picture
  play/src/front/Components/EmbedScreens/CamerasContainer.svelte
  play/src/front/Components/Video/PictureInPicture.svelte
  play/src/front/Stores/StreamableCollectionStore.ts
Labels: deploy, size:M

#5180 Refactoring live streaming store
  play/src/front/Components/ActionBar/MegaphoneConfirm.svelte
  play/src/front/Components/ActionBar/MenuIcons/MapSubMenu.svelte
  play/src/front/Components/Modal/GlobalCommunicationModal.svelte
  play/src/front/Phaser/Game/MapEditor/AreasPropertiesListener.ts
  play/src/front/Space/Space.ts
  play/src/front/Space/SpaceInterface.ts
  play/src/front/Space/SpaceRegistry/SpaceRegistry.ts
  play/src/front/Space/SpaceRegistry/SpaceRegistryInterface.ts
  play/src/front/Space/Utils/SpaceScriptingBridge.ts
  play/src/front/Stores/IsStreamingStore.ts
  play/src/front/Stores/MediaStore.ts
  play/src/front/Stores/StreamableCollectionStore.ts
Labels: size:L
