Repository workadventure/workadventure, pull requests merged in 2025-08, with the labels that each got.

#5001 pt-BR traduction
  play/src/i18n/pt-BR/actionbar.ts
  play/src/i18n/pt-BR/area.ts
  play/src/i18n/pt-BR/audio.ts
  play/src/i18n/pt-BR/camera.ts
  play/src/i18n/pt-BR/cowebsite.ts
  play/src/i18n/pt-BR/externalModule.ts
  play/src/i18n/pt-BR/form.ts
  play/src/i18n/pt-BR/index.ts
  play/src/i18n/pt-BR/login.ts
  play/src/i18n/pt-BR/mapEditor.ts
  play/src/i18n/pt-BR/megaphone.ts
  play/src/i18n/pt-BR/menu.ts
  play/src/i18n/pt-BR/messageScreen.ts
  play/src/i18n/pt-BR/notification.ts
  play/src/i18n/pt-BR/refreshPrompt.ts
  play/src/i18n/pt-BR/say.ts
  play/src/i18n/pt-BR/statusModal.ts
  play/src/i18n/pt-BR/trigger.ts
  play/src/i18n/pt-BR/video.ts
  play/src/i18n/pt-BR/warning.ts
  play/src/i18n/pt-BR/woka.ts
Labels: size:XL

#5004 fix entity delete and mapeditor open
  play/src/front/Components/PopUp/PopUpDropFileEntity.svelte
  play/src/front/Phaser/Game/MapEditor/Tools/EntityEditorTool.ts
  play/src/front/Phaser/Game/MapEditor/Tools/EntityRelatedEditorTool.ts
Labels: size:S

#5007 fix upload file ui
  play/src/front/Components/PopUp/DropFileEntityPicker.svelte
  play/src/front/Components/PopUp/PopUpDropFileEntity.svelte
Labels: size:XS

#5003 Improve UI
  play/src/front/Components/HelpSettings/HelpCameraSettingsPopup.svelte
  play/src/front/Components/HelpSettings/HelpNotificationSettingPopup.svelte
  play/src/front/Components/Input/Input.svelte
  play/src/front/Components/Input/RangeSlider.svelte
  play/src/front/Components/Input/Select.svelte
  play/src/front/Components/MapEditor/AreaEditor/AreaPropertiesEditor.svelte
  play/src/front/Components/MapEditor/ConfigureMyRoom/Megaphone.svelte
  play/src/front/Components/MapEditor/PropertyEditor/FocusablePropertyEditor.svelte
  play/src/front/Components/MapEditor/PropertyEditor/JitsiRoomPropertyEditor.svelte
  play/src/front/Components/MapEditor/PropertyEditor/MatrixRoomPropertyEditor.svelte
  play/src/front/Components/MapEditor/PropertyEditor/OpenFilePropertyEditor.svelte
  play/src/front/Components/MapEditor/PropertyEditor/OpenWebsitePropertyEditor.svelte
  play/src/front/Components/MapEditor/PropertyEditor/PersonalAreaPropertyEditor.svelte
  play/src/front/Components/MapEditor/PropertyEditor/PlayAudioPropertyEditor.svelte
  play/src/front/Components/MapEditor/PropertyEditor/PropertyEditorBase.svelte
  play/src/front/Components/MapEditor/PropertyEditor/TooltipPropertyButton.svelte
  play/src/front/Components/Modal/GlobalCommunicationModal.svelte
  play/src/front/style/map-editor.scss
  play/src/i18n/ar-SA/mapEditor.ts
  play/src/i18n/de-DE/mapEditor.ts
  play/src/i18n/en-US/mapEditor.ts
  play/src/i18n/fr-FR/mapEditor.ts
  play/src/i18n/it-IT/mapEditor.ts
  play/src/i18n/ja-JP/mapEditor.ts
  play/src/i18n/nl-NL/mapEditor.ts
  play/src/i18n/pt-BR/mapEditor.ts
Labels: size:L

#5009 fix delete entity and preview
  play/src/front/Components/PopUp/PopUpDropFileEntity.svelte
  play/src/front/Phaser/Game/MapEditor/Tools/EntityEditorTool.ts
  play/src/front/Phaser/Game/MapEditor/Tools/EntityRelatedEditorTool.ts
Labels: size:M

#5011 set filedropped to false
  play/src/front/Phaser/Game/MapEditor/Tools/EntityRelatedEditorTool.ts
Labels: size:XS

#5012 Fixing build on forks
  .github/workflows/build-multi-arch-image.yml
  .github/workflows/build-single-image.yml
  .github/workflows/build-test-and-deploy.yml
Labels: size:S

#5017 Fixing height of container in PiP mode
  play/src/front/Components/EmbedScreens/CamerasContainer.svelte
Labels: size:XS

#5025 Improve calendar and todolist UI
  play/src/front/Components/Calendar/Calendar.svelte
  play/src/front/Components/TodoList/TodoList.svelte
Labels: size:S

#5030 Trying to make E2E tests more robust
  play/src/front/Components/MapEditor/EntityEditor/EntityUpload/EntityUpload.svelte
  tests/tests/utils/map-editor/entityEditor.ts
Labels: size:XS

#5031 Adding support for a "no-flaky" flag
  .github/workflows/build-test-and-deploy.yml
  tests/playwright.config.ts
Labels: size:M, no-flaky

#5037 Trying more resilient E2E search entity
  tests/tests/utils/map-editor/entityEditor.ts
Labels: size:S, no-flaky

#5041 Stabilizing E2E test for youtube embeds
  libs/shared-utils/src/Application/Exception/GoogleWorkSpaceException.ts
  libs/shared-utils/src/Application/YoutubeService.ts
  play/src/front/Chat/Components/Room/Application/ApplicationFormWrapper.svelte
  play/src/front/Chat/Components/Room/MessageInputBar.svelte
Labels: deploy, size:M, no-flaky

#5045 Update troubleshooting.md with windows git config
  docs/others/troubleshooting.md
Labels: size:S

#5052 Fix zoom on focusable area
  play/src/front/Phaser/Game/CameraManager.ts
Labels: deploy, size:S

#5056 Adding possiblity to disable generating source maps
  play/vite.config.ts
Labels: size:XS

#5057 fix upload doc design
  play/src/front/Components/MapEditor/PropertyEditor/FileUpload/FileUpload.svelte
  play/src/front/Components/MapEditor/PropertyEditor/PropertyEditorBase.svelte
  play/src/front/Components/PopUp/PopUpDropFileEntity.svelte
Labels: size:M

#5060 Add FAST_BUILD argument to control build mode for play image
  .github/workflows/build-single-image.yml
  play/Dockerfile
Labels: deploy, linked_to_saas_branch, size:XS

#5059 Adding a "summary" to the i18n:diff command
  .github/copilot-instructions.md
  docs/others/contributing/how-to-translate.md
  play/scripts/diff-i18n.ts
Labels: size:L

#5063 Update Share button and page
  play/src/front/Components/ActionBar/ActionBarButton.svelte
  play/src/front/Components/ActionBar/MenuIcons/InviteMenuItem.svelte
  play/src/front/Components/Icons/LocationIcon.svelte
  play/src/front/Components/Icons/ShareIcon.svelte
  play/src/front/Components/Menu/GuestSubMenu.svelte
  play/src/i18n/de-DE/menu.ts
  play/src/i18n/en-US/menu.ts
  play/src/i18n/fr-FR/menu.ts
  tests/tests/iframe_script.spec.ts
  tests/tests/mobile/iframe_script.spec.ts
  tests/tests/oidc.spec.ts
  tests/tests/responsive_actionbar.spec.ts
Labels: size:L

#5065 Fixing unstable test in Kube
  tests/tests/room-api.spec.ts
Labels: deploy, size:M

#5071 Adding 2 videos in the OpenFile property documentation
  docs/map-building/inline-editor/area-editor/open-file.md
  docs/map-building/inline-editor/entity-editor/open-file.md
Labels: size:S
