Repository workadventure/workadventure, pull requests merged in 2025-07, with the labels that each got.

#4949 Fixed the Tools Editing Zone
  play/src/front/Phaser/Components/MapEditor/AreaPreview.ts
Labels: size:S

#4952 Improve to manage icon of add in for calendar and todolist
  play/src/front/Components/Calendar/Calendar.svelte
  play/src/front/Components/TodoList/TodoList.svelte
  play/src/front/Stores/Utils/externalSvelteComponentService.ts
  play/src/i18n/en-US/externalModule.ts
  play/src/i18n/fr-FR/externalModule.ts
Labels: size:M

#4957 Add S3 configuration options for connection and request timeouts
  map-storage/src/Enum/EnvironmentVariable.ts
  map-storage/src/Enum/EnvironmentVariableValidator.ts
  map-storage/src/Services/S3Client.ts
Labels: size:S

#4955 Improve analytics for "All settings" menu
  play/src/front/Administration/AnalyticsClient.ts
  play/src/front/Components/Menu/Menu.svelte
Labels: size:S

#4958 Improve calendar and todo list component
  play/src/front/Components/Calendar/Calendar.svelte
  play/src/front/Components/TodoList/TodoList.svelte
  play/src/front/Stores/Utils/externalSvelteComponentService.ts
  play/src/i18n/en-US/externalModule.ts
  play/src/i18n/fr-FR/externalModule.ts
Labels: size:M

#4960 Improve add in
  play/src/front/Components/Calendar/Calendar.svelte
  play/src/front/Components/TodoList/TodoList.svelte
  play/src/front/Components/images/applications/calendar.png
  play/src/front/Components/images/applications/task.png
  play/src/front/Connection/ConnectionManager.ts
  play/src/i18n/en-US/externalModule.ts
  play/src/pusher/controllers/AuthenticateController.ts
  play/src/pusher/services/OpenIDClient.ts
Labels: size:M

#4959 Fix issues on file upload
  play/src/front/Components/MapEditor/PropertyEditor/FileUpload/FileUpload.svelte
  play/src/front/Components/MapEditor/PropertyEditor/OpenFilePropertyEditor.svelte
  play/src/front/Components/PopUp/PopupFile.svelte
  play/src/front/Phaser/Game/MapEditor/AreasPropertiesListener.ts
Labels: size:M

#4965 Fix userlist scrolling
  play/src/front/Chat/Components/UserList/RoomUserList.svelte
Labels: size:XS

#4966 Improve audio manager
  play/src/front/Components/ActionBar/MenuIcons/ContextualMenuItems.svelte
  play/src/front/Components/AudioManager/AudioManager.svelte
  play/src/front/Components/AudioManager/AudioPlayer.svelte
  play/src/i18n/en-US/audio.ts
  play/src/i18n/fr-FR/audio.ts
  tests/tests/areas.spec.ts
Labels: size:M

#4969 Improve UI to stack popup component for "centered zone"
  play/src/front/Components/ExternalModules/ExternalComponents.svelte
  play/src/front/Components/MapEditor/ClaimPersonalAreaDialogBox.svelte
Labels: size:S

#4913 New customize scene
  play/src/front/Chat/Components/Room/Reaction.svelte
  play/src/front/Components/ActionBar/EmojiSubMenu.svelte
  play/src/front/Components/App.svelte
  play/src/front/Components/AudioManager/AudioManager.svelte
  play/src/front/Components/AudioManager/AudioPlayer.svelte
  play/src/front/Components/EmbedScreens/CamerasContainer.svelte
  play/src/front/Components/GameOverlay.svelte
  play/src/front/Components/HelpSettings/HelpWebRtcSettingsPopup.svelte
  play/src/front/Components/Icons/BodyIcon.svelte
  play/src/front/Components/Icons/EyesIcon.svelte
  play/src/front/Components/Icons/HairIcon.svelte
  play/src/front/Components/Icons/HangerIcon.svelte
  play/src/front/Components/Icons/HatIcon.svelte
  play/src/front/Components/Icons/ShuffleIcon.svelte
  play/src/front/Components/Icons/SwordIcon.svelte
  play/src/front/Components/MapEditor/AreaEditor/AreaPropertiesEditor.svelte
  play/src/front/Components/PopUp/SayPopUp.svelte
  play/src/front/Components/SelectCharacter/SelectCharacterCustomizeScene.svelte
  play/src/front/Components/SelectCharacter/SelectCharacterScene.svelte
  play/src/front/Components/Util/Tooltip.svelte
  play/src/front/Components/VisitCard/VisitCard.svelte
  play/src/front/Components/Woka/WokaCustomizeScene.svelte
  play/src/front/Components/Woka/WokaPreview.svelte
  play/src/front/Components/Woka/WokaScene.svelte
  play/src/front/Components/Woka/WokaSelectScene.svelte
  play/src/front/Components/Woka/WokaTypes.ts
  play/src/front/Phaser/Game/GameManager.ts
  play/src/front/Phaser/Login/CustomizeScene.ts
  play/src/front/Phaser/Login/SelectCharacterScene.ts
  play/src/front/Phaser/UserInput/GameSceneUserInputHandler.ts
  play/src/front/Stores/MenuStore.ts
  play/src/front/Stores/SelectCharacterStore.ts
  play/src/front/Streaming/Jitsi/JitsiBroadcastSpace.ts
  play/src/i18n/ar-SA/woka.ts
  play/src/i18n/ca-ES/woka.ts
  play/src/i18n/de-DE/woka.ts
  play/src/i18n/dsb-DE/woka.ts
  play/src/i18n/en-US/woka.ts
  play/src/i18n/es-ES/woka.ts
  play/src/i18n/fr-FR/woka.ts
  play/src/i18n/hsb-DE/woka.ts
  play/src/i18n/it-IT/woka.ts
  play/src/i18n/ja-JP/woka.ts
  play/src/i18n/nl-NL/woka.ts
  play/src/i18n/pt-BR/woka.ts
  play/src/i18n/zh-CN/woka.ts
Labels: deploy, size:XXL

#4975 Expose map explorer shortcut
  play/src/front/Components/ActionBar/MenuIcons/MapEditorMenuItem.svelte
  play/src/front/Components/ActionBar/MenuIcons/MapSubMenuContent.svelte
  play/src/i18n/fr-FR/actionbar.ts
  tests/tests/map_editor.spec.ts
  tests/tests/utils/menu.ts
Labels: size:M

#4979 Improve UI UX for responsive select WOKA scene
  play/src/front/Components/Woka/WokaCustomizeScene.svelte
  play/src/front/Components/Woka/WokaSelectScene.svelte
Labels: size:S

#4971 Drag drop files
  libs/map-editor/pdf-test/lorem-ipsum.pdf
  map-storage/src/MapStorageServer.ts
  play/src/front/Administration/AnalyticsClient.ts
  play/src/front/Components/App.svelte
  play/src/front/Components/DroppingFile/DroppingFileScene.svelte
  play/src/front/Components/GameOverlay.svelte
  play/src/front/Components/MapEditor/PropertyEditor/OpenFilePropertyEditor.svelte
  play/src/front/Components/PopUp/DropFileEntityPicker.svelte
  play/src/front/Components/PopUp/PopUpConnect.svelte
  play/src/front/Components/PopUp/PopUpDropFileEntity.svelte
  play/src/front/Components/PopUp/PopUpFile.svelte
  play/src/front/Connection/RoomConnection.ts
  play/src/front/Phaser/FileUpload/FileListener.ts
  play/src/front/Phaser/Game/MapEditor/AreasPropertiesListener.ts
  play/src/front/Phaser/Game/MapEditor/MapEditorModeManager.ts
  play/src/front/Phaser/Game/MapEditor/Tools/EntityEditorTool.ts
  play/src/front/Phaser/Game/MapEditor/Tools/EntityRelatedEditorTool.ts
  play/src/front/Stores/FileUploadStore.ts
  play/src/front/Stores/MapEditorStore.ts
  play/src/i18n/en-US/mapEditor.ts
  play/src/i18n/fr-FR/mapEditor.ts
  tests/tests/map_editor.spec.ts
Labels: size:XL

#4986 Fix mobile UI
  play/src/front/Components/GameOverlay.svelte
  play/src/front/Components/Woka/WokaCustomizeScene.svelte
  play/src/front/Components/Woka/WokaSelectScene.svelte
Labels: deploy, size:S

#4989 Fix mobile ui
  play/src/front/Chat/ChatSidebar.svelte
  play/src/front/Chat/Components/UserList/User.svelte
  play/src/front/Phaser/Entity/RemotePlayer.ts
  play/src/front/style/chat.scss
Labels: size:L

#4991 Fix credit card detection by Chrome
  play/src/front/Components/Login/LoginScene.svelte
  play/src/front/Phaser/Entity/RemotePlayer.ts
  tests/tests/error_pages.spec.ts
  tests/tests/utils/auth.ts
Labels: size:S

#4990 remove entity highlight after drag and drop
  play/src/front/Components/MapEditor/EntityEditor/EntityPropertiesEditor.svelte
Labels: size:XS

#4887 Added a send message button in the woka menu VisitCard
  play/src/front/Components/ActionsMenu/WokaMenu.svelte
  play/src/front/Components/VisitCard/VisitCard.svelte
  play/src/front/Components/images/chat.png
  play/src/front/Phaser/Game/MapEditor/AreasPropertiesListener.ts
Labels: size:M

#4916 Move the personal area only in the admin
  play/src/front/Components/MapEditor/AreaEditor/AreaPropertiesEditor.svelte
  tests/tests/map_editor_area_rights.spec.ts
Labels: size:L

#4996 rename map menu
  play/src/i18n/en-US/actionbar.ts
  play/src/i18n/fr-FR/actionbar.ts
Labels: size:XS
