Repository workadventure/workadventure, pull requests merged in 2025-06, with the labels that each got.

#4901 Properly encoding the room name in the websocket connection
  play/src/front/Connection/RoomConnection.ts
Labels: size:XS

#4903 [ChatConnection] : moved callback out of Promise.all to ensure it always runs
  play/src/front/Phaser/Game/GameScene.ts
Labels: size:S

#4899 Changing the way bubbles are displayed
  back/src/Model/GameRoom.ts
  back/src/Model/Group.ts
  back/src/Model/PositionNotifier.ts
  back/src/Model/Zone.ts
  back/src/Services/SocketManager.ts
  back/tests/GameRoom.test.ts
  back/tests/PositionNotifier.test.ts
  messages/protos/messages.proto
  play/src/front/Connection/ConnexionModels.ts
  play/src/front/Connection/RoomConnection.ts
  play/src/front/Phaser/Entity/ConversationBubble.ts
  play/src/front/Phaser/Game/DepthIndexes.ts
  play/src/front/Phaser/Game/GameScene.ts
  play/src/pusher/models/Zone.ts
  play/src/pusher/services/SocketManager.ts
Labels: deploy, size:XL

#4906 Fixing the ingress for single domain deployments
  contrib/helm/templates/ingress-root.yaml
Labels: size:M

#4905 Switch back to express
  back/package.json
  back/src/App.ts
  back/src/Controller/DebugController.ts
  back/src/Controller/PingController.ts
  back/src/Controller/PrometheusController.ts
  back/src/Server/server/app.ts
  back/src/Server/server/baseapp.ts
  back/src/Server/server/formdata.ts
  back/src/Server/server/sslapp.ts
  back/src/Server/server/types.ts
  back/src/Server/server/utils.ts
  back/src/Server/sifrr.server.ts
  package-lock.json
Labels: size:L

#4896 Some design fixes in the map editor
  play/src/front/Components/MapEditor/EntityEditor/CustomEntityEditionForm/CustomEntityEditionForm.svelte
Labels: size:XS

#4911 refactor: simplify URL construction for room connection
  play/src/front/Connection/RoomConnection.ts
Labels: size:M

#4912 Fix subtitle in reconnecting screen
  play/src/i18n/en-US/messageScreen.ts
  play/src/i18n/fr-FR/messageScreen.ts
Labels: size:XS

#4918 Upgrading DOMPurify
  package-lock.json
  play/package.json
Labels: size:XS

#4939 refactor: move locale detection tests to proper location and test real implementation
  play/src/front/Utils/locales.ts
  play/tests/front/Utils/locales.test.ts
Labels: deploy, size:L

#4943 Add secret key to mapstorage container in Helm chart
  .env.template
  contrib/docker/docker-compose.prod.yaml
  contrib/helm/templates/mapstorage-deployment.yaml
Labels: deploy, size:S

#4930 Fix design of personal area property editor
  play/src/front/Components/Input/ButtonClose.svelte
  play/src/front/Components/MapEditor/PropertyEditor/PersonalAreaPropertyEditor.svelte
Labels: size:S
