Repository workadventure/workadventure, pull requests merged in 2025-10, with the labels that each got.

#5194 Fixing PiP triggered when alone
  play/src/front/Components/Video/PictureInPicture.svelte
Labels: size:S

#5195 Turning off webcam and mic when exiting a Livekit room
  play/src/front/Livekit/LiveKitRoom.ts
Labels: size:XS

#5191 Fixing the flicker when coming back to a tab
  back/src/Services/GaugeManager.ts
  livekit-config.yaml
  play/src/front/Phaser/Game/GameScene.ts
  play/src/front/Phaser/Player/Player.ts
Labels: size:M

#5198 Merge develop into master
  .github/workflows/build-test-and-deploy.yml
  contrib/helm/templates/mapstorage-deployment.yaml
  play/src/front/Components/Cowebsites/JistiCowebsiteComponent.svelte
  play/src/front/Phaser/Game/GameMap/GameMapFrontWrapper.ts
  tests/tests/chat/matrixChat.spec.ts
  tests/tests/map_editor.spec.ts
Labels: size:S

#5201 Correctly initializing the characters depth.
  play/src/front/Phaser/Entity/Character.ts
Labels: size:XS

#5202 Fix Eraser app regarding embeddable changes in the map editor
  play/src/front/Components/MapEditor/AreaEditor/AreaPropertiesEditor.svelte
Labels: size:XS

#5207 fix cancel screenshare
  play/src/front/Stores/ScreenSharingStore.ts
Labels: size:XS
